config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users
  root 'welcome#index'

  resources :articles
  #resources :articles, except: [:delete]
  #resources :articles, only: [:create, :show]
  #get 'special', to: "welcome#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, uniqueness: true
	validates :body, presence:true, length: {minimum: 20}
	#validates :username, format: {with: expresion refular}
	before_create :set_visits_count
	#before_save
	#before_validation
	#after_create

	def update_visits_count
		self.update(visits_count: self.visits_count + 1)
		
		
	end

	private
	def set_visits_count
		self.visits_count = 0;
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except:[:show,:index]
	before_action :set_article, except: [:index, :new, :create]
	#GET /articles
	def index
		#Obtiene todos los registros de la tabla
		@articles = Article.all
	end

	#GET /articles/:id
	def show
		#Va a encontrar un registro por su id
		#@article = Article.find(params[:id])

		@article.update_visits_count

		#devuelve un arreglo
		#Article.where("id: ?",params[:id])
		#Article.where("id: ? AND title",params[:id], paramas[:title])
		#Article.where("id: ? OR title",params[:id], paramas[:title])

		#WHERE
		#Article.where("body LIKE  ?","%hola%")

		#Articulos diferentes a los parametros
		#Article.where.not("id = 1")
		#Article.where.not("id = 1").count
	end

	#GET /articles/new
	def new
		@article = Article.new

	end

	#POST /articles
	def create
		# @article = Article.new(title: params[:article][:title], 
		# 						body:params[:article][:body])
		@article = current_user.articles.new(article_params)


		#@article.invalid?
		if @article.save
			redirect_to @article
		else
			render :new
		end		
	end


	def edit
		#@article = Article.find(params[:id])
	end

	#PUT /articles/:
	def update
		#@article.update_attributes({title: 'nuevo titulo'})
		#@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	#DELETE /articles/:id
	def destroy
		#@article = Article.find(params[:id])
		@article.destroy #Destroy elimina el objeto de la base de datos
		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :body)
	end

	def set_article
		@article = Article.find(params[:id])
	end

	def validate_user
		redirect_to new_user_session_path, notice: "Necesitas iniciar sesión"
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% accion ||= "Crear" %>
<h1><%= accion%> Artículo</h1>
<%= form_for(@article) do |f| %>
	
	
	<% @article.errors.full_messages.each do |message| %>
		*<%= message%>
		<br>
	<% end	%>


	<div class="form-group">
	    <label for="exampleInputEmail1">Titulo</label>
	    <%= f.text_field :title, placeholder: "Titulo", class: "form-control" %>
  	</div>

  	<div class="form-group">
	    <label for="exampleInputEmail1">Cuerpo</label>
	    <%= f.text_area :body, placeholder: "Escribe tu articulo", class: "form-control"%>
  	</div>

  	<%= f.submit "Guardar", class: "btn btn-default" %>

<% end %>

app/views/articles/edit.html.erb
<%= render "form", accion: 'Editar'%>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div>
		<%= article.body %> - <%= link_to "Eliminar", article, method: :delete, class: "btn btn-danger btn-xs"%>
	</div>
<% end %>

app/views/articles/new.html.erb
<%= render "form", accion: 'Crear'%>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<% unless @article.user.nil? %>
	<p>
		Escrito por: <%= @article.user.email %>
	</p>

	<p>
		Visitas: <%= @article.visits_count %>
	</p>
<% end %>

<div>
	<%= @article.body %>
</div>

<%= link_to "Editar", edit_article_path(@article) %>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :article_id %>
    <%= f.text_field :article_id %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "partials/navigation" %>

  <div class="container">
  	<body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
	    <%= yield %>
	  </body>
  </div>
</html>

app/views/partials/_navigation.html.erb
 	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container">

			<%= link_to "Home", root_path, class: "navbar-brand"%>
            <ul class="nav navbar-nav">
                <li class="active"><a href="">Diseño</a></li>
                <li><a href="">Programación</a></li>
                <li><a href="">Tecnología</a></li>
            </ul>

            <% if user_signed_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
              </ul>
            <% else %>
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
                    <li><%= link_to "Crear cuenta", new_user_registration_path %></li>
                </ul>
            <% end %>
            
		</div>
	</nav>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<h1>Bienvenido <%= current_user.email %></h1>
<% end %>